version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Мапим порт приложения на хост
    environment:
      - PORT=${PORT}
      - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433" # Для доступа к БД с хоста (опционально)
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgres-data: